baseURL: https://hntk03.github.io/
languageCode: ja
title: hntk03's Portfolio
theme: "PaperMod"
publishDir: "docs"
canonifyurls: true

params:
    defaultTheme: light
    # defaultTheme: dark
    #defaultTheme: auto # to switch between dark or light according to browser theme
params:
    homeInfoParams:
        Title: Hi there wave
        Content: Can be Info, links, about...

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/hntk03"
