baseURL: https://hntk03.github.io/
languageCode: ja
title: hntk03's Portfolio
canonifyurls: true
theme: "PaperMod"
publishDir: "docs"

params:
    defaultTheme: light
    # defaultTheme: dark
    #defaultTheme: auto # to switch between dark or light according to browser theme
    homeInfoParams:
        Title: Works
        Content: 作った物を紹介

    socialIcons: # optional
        - name: "Github"
          url: "https://github.com/hntk03"

menu:
  main:
    - identifier: profile
      name: Profile
      url: /posts/profile/
      weight: 1
